name: lemmy_dart_client
description: Future-based http client for the Lemmy API. Provides an easy interface and statically typed responses.
version: 1.0.0
repository: https://github.com/thunder-app/lemmy_dart_client

environment:
  sdk: ^3.6.0

dependencies:
  json_annotation: ^4.9.0
  http: ^1.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.13
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
